FROM golang:1.26.1-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY backend ./backend

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /kitsu-ingester ./backend/cmd/ingester

FROM alpine:3.20

WORKDIR /app

COPY --from=builder /kitsu-ingester /usr/local/bin/kitsu-ingester

CMD ["kitsu-ingester"]